/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode;

import org.junit.Test;
import static org.junit.Assert.*;

public class LC1Test {
    @Test public void testLc1() {
        var lc = new LC1();
        assertArrayEquals(new int[]{0, 1}, lc.solution1(new int[]{2, 7, 11, 15}, 9));
        assertArrayEquals(new int[]{1, 2}, lc.solution1(new int[]{3, 2, 4}, 6));
    }
}
